name: sanalira_flutter_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  http: ^0.13.5
  cupertino_icons: ^1.0.2
  clipboard:
  toast: ^0.3.0
  flutter_secure_storage: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/banka_icon/
    - assets/flags/
    - assets/navigation_bar_icon/
    - assets/register_screen_icon/
